// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocjoucqydgclmicmsmip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jam91Y3F5ZGdjbG1pY21zbWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MzQxODcsImV4cCI6MjA2ODExMDE4N30.Ngmc48dblOOOJ_bsJ75IAAtTqITMKCoH0VcZtHUy9Aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});